export const CHANGE_MOVIES_TAB = 'CHANGE_MOVIES_TAB';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_IN_THEATERS = 'FETCH_MOVIES_IN_THEATERS';
export const FETCH_MOVIES_COMING_SOON = 'FETCH_MOVIES_COMING_SOON';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';

export const FETCH_MOVIES_QUERY = 'FETCH_MOVIES_QUERY';
export const CLEAR_MOVIES_QUERY = 'CLEAR_MOVIES_QUERY';

export const UPDATE_MOVIES_SEARCH_STEP = 'UPDATE_MOVIES_SEARCH_STEP';

export const FETCH_MOVIES_SUBJECT = 'FETCH_MOVIES_SUBJECT';